services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    container_name: 'nginx'
    image: nginx:1.25.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/web-server:/etc/nginx/conf.d

  php:
    container_name: 'php'
    restart: unless-stopped
    build:
      context: ./docker/php
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    volumes:
      - ./:/var/www

volumes:
  postgres_data:
    driver: local
